# Generated by Django 4.1.13 on 2024-02-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='prompt',
            field=models.TextField(default=None, null=True),
        ),
    ]
