# Generated by Django 4.1.13 on 2024-02-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0002_summary_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='format',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='persona',
            field=models.TextField(default=None, null=True),
        ),
    ]
