# Generated by Django 4.1.13 on 2024-02-24 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0003_summary_format_summary_persona'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='summary',
            unique_together={('text', 'prompt', 'persona', 'format', 'config')},
        ),
    ]
