# Generated by Django 4.1.13 on 2024-02-24 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0004_alter_summary_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='stats',
        ),
    ]
