# Generated by Django 4.1.13 on 2024-02-25 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0005_remove_summary_stats'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='summary',
            unique_together=set(),
        ),
    ]
