# Generated by Django 4.1.13 on 2024-05-14 04:10

from django.db import migrations
import systems.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0006_alter_summary_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='endings',
            field=systems.models.fields.ListField(default=list),
        ),
    ]
