# Generated by Django 4.1.13 on 2024-11-24 11:32

from django.db import migrations
import systems.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0007_summary_endings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='text',
            field=systems.models.fields.ListField(default=list),
        ),
    ]
