_base_model: &base_model
    base: id_resource
    key: id
    admin_roles: [data-admin]
    view_roles: [data-auditor]
    priority: 60

models:
    summary:
        <<: *base_model
        plural: summaries
        id_fields: []
        name_field: false
        key: id
        display: "<id>"
        priority: 65
        fields:
            text:
                type: list

            prompt:
                type: text
            persona:
                type: text
            format:
                type: text
            endings:
                type: list
            config:
                type: dict

            result:
                type: text

            request_tokens:
                type: integer
            response_tokens:
                type: integer
            cost:
                type: float
